---
version: 2

plan:
  project-key: BUSDM
  name: WT-106 release 1.13
  key: DMSUPPREL

branches:
  create:
    for-new-branch: \w+/\w+/\d\..*
  delete:
    after-deleted-days: 7
    after-inactive-days: 180
  link-to-jira: true

stages:
  - Default Stage:
      jobs:
        - Default Job

Default Job:
  docker:
    broadbandforum/report-pl:develop

  tasks:
    - clean
    - checkout:
        repository: wt-106-release-1-13
        path: WT-106
    - checkout:
        repository: install-develop
        path: install
    - script: |
        make --directory=WT-106 SUBDIRSEXCLUDE=specification test.report-pl
        make --directory=WT-106 test.pandoc
    - test-parser:
        type: junit
        test-results:
          - WT-106/docs/*-tests.xml

  artifacts:
    - name: all
      location: WT-106
      pattern: '**'
      required: true
      shared: true

    - name: PROJECT
      location: WT-106/docs/PROJECT
      pattern: '**'
      required: false
      shared: false

    - name: data-model-template
      location: WT-106/docs
      pattern: '**'
      required: false
      shared: false

    - name: HTML
      location: WT-106/support/docs
      pattern: '*.html'
      required: false
      shared: false

    - name: DOCX
      location: WT-106/docs
      pattern: '*.docx'
      required: false
      shared: false

    - name: PDF
      location: WT-106/docs
      pattern: 'WT-106-*.pdf'
      required: false
      shared: false
